### ISSUE TITLE
add schema file to config

### ISSUE THREAD

**Issue by escapewindow** [mozilla-releng/scriptworker#107]
https://github.com/taskcluster/taskcluster-rfcs/issues/22#issuecomment-291994145 :
> We could have part of the scriptworker.yaml config point at a jsonschema file though.

We could point at a super generic schema file by default, and allow each scriptworker instance to provide a more explicit one.

It might be tricky to figure out paths when it's installed in the virtualenv...  we can figure it out.

**Comment by JohanLorenzo** [comment]
For what it's worth, #196 added (optional) schema verification at the scriptworker level. The path is provided by the script config, which is also loaded at the scriptworker level.

**Comment by escapewindow** [comment]
Nice :)
