### ISSUE TITLE
allow for generic script workflow

### ISSUE THREAD

**Issue by escapewindow** [mozilla-releng/scriptworker#115]
Right now, creating scripts for scriptworker is a bit more involved than it should be.  Not only do the scripts have to perform the action, but they also have to verify the schema and scopes before proceeding.  It would be good if we could get scriptworker to do some of this.

For example, in scriptworker.yml we could allow for a task jsonschema file.  We could add a dict of scopes to script commandlines (this would need some way to specify getting info from the task definition).

If we make these changes, many scripts may be runnable in scriptworker without [as many?] changes.

**Comment by MihaiTabara** [comment]
Not sure how prioritized this is but I'd love to sign-up for this. It would be a great opportunity for me to dive in better in the scriptworker internal kitchen.

**Comment by escapewindow** [comment]
#195 is probably good here.
