### ISSUE TITLE
Allow scriptworker to download artifacts even if chain of trust isn't enabled

### ISSUE THREAD

**Issue by JohanLorenzo** [mozilla-releng/scriptworker#121]
In [bug 1366094](https://bugzilla.mozilla.org/show_bug.cgi?id=1366094), we had to partially enable chain of chain of trust, because we need artifacts to be downloaded. In pushapkscript, if somedody wants to hack on the script, without chain of trust enabled, they have to [trick the script](https://github.com/mozilla-releng/pushapkscript#do-i-need-to-activate-chain-of-trust-for-local-development).

I think we now want a way to download artifacts for instances that don't have CoT enabled. One way I see: Make [this line](https://github.com/mozilla-releng/scriptworker/blob/601fcf23103c9893e8ea44678fe6e41b4ae73691/scriptworker/artifacts.py#L305) run if CoT is enabled. Otherwise, output a warning like `WARNING : Artifacts are downloaded without Chain of Trust. There is no assurance about the origin of the artifacts` and download anyway.

What do you think @escapewindow ?

**Comment by escapewindow** [comment]
We only run `download_firefox_cot_artifacts` during chain of trust verification: https://github.com/mozilla-releng/scriptworker/blob/601fcf23103c9893e8ea44678fe6e41b4ae73691/scriptworker/cot/verify.py#L1266

That helps us verify the artifacts, but also requires chain of trust verification to get the artifacts to test. We can move this call to just before [this line in `async_main`](https://github.com/mozilla-releng/scriptworker/blob/601fcf23103c9893e8ea44678fe6e41b4ae73691/scriptworker/worker.py#L55) and then verify their shas during chain of trust verification, maybe.

We might be able to keep the `validate_artifact_url` call anyway. If we end up wanting to point at random binaries for dev testing, then yes, we can put in a flag to ignore that.

**Comment by JohanLorenzo** [comment]
It turns out that's needed by [Bug 1374589](https://bugzilla.mozilla.org/show_bug.cgi?id=1374589) on Try. I'm going to work on this issue.

**Comment by escapewindow** [comment]
It's probably better to enable unsigned cot on try, if possible.

**Comment by JohanLorenzo** [comment]
It turns out https://github.com/mozilla-releng/scriptworker/issues/121#issuecomment-313693972 is wrong. See [Bug 1374589 comment 12](https://bugzilla.mozilla.org/show_bug.cgi?id=1374589#c12)

**Comment by escapewindow** [comment]
Let's wontfix for now. If we get another valid use case, we can revisit.
