### ISSUE TITLE
graceful shutdown support

### ISSUE THREAD

**Issue by escapewindow** [mozilla-releng/scriptworker#204]
Send a signal? touch a file? and shut down after the current task finishes (or immediately if no current task).

We'd have to combine this with supervisorctl somehow, if we want it to stay down.

**Comment by tomprince** [comment]
Looking at the [supervisord docs](http://supervisord.org/configuration.html#program-x-section-values), it looks like it sends `SIGTERM` when requested to stop a task. If we put a long enough timeout for stopping, we can use supervisor to control shutting down.

**Comment by escapewindow** [comment]
SGTM :)

**Comment by escapewindow** [comment]
Sounds like we got graceful shutdown support in #190.
