### ISSUE TITLE
Support multiple schemas validations

### ISSUE THREAD

**Issue by MihaiTabara** [mozilla-releng/scriptworker#223]
Currently `beetmoverscript` and `shipitscript` support more than one behavior (where a behavior is usually defined by a separate `action` type), hence multiple schemas validation to take care of. For all these cases, we can't take advantage of scriptworker's implicit validation, at least not in an elegant way.

Beetmover was the first one with multiple behaviors and frankly, is still a mess from this perspective (`nightly` and `release` schemas where former is almost inexisting in unittesting, etc). Now, with adding multiple behaviors in `shipitscript`, it might be handy to enable that in order to reduce the boilerplate code we need.

Ah, just reminded, I think we have multiple behaviors in `bouncerscript` as well (submission + aliases). I've been doing mostly tiny reviews in this project so far so I'd love if I could take care of implementing this in order to get even more confortable with the code.

**Comment by escapewindow** [comment]
We can support multiple schemas, or use [anyOf](http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.7.2) to list an array of valid schemas.

**Comment by tomprince** [comment]
:+1: to using `anyOf`.

**Comment by escapewindow** [comment]
We're currently using flexible schemas, where certain keys are optional, and performing any additional checks in-script. Is that sufficient @MihaiTabara ?

**Comment by escapewindow** [comment]
Let's close, since we can use `anyOf`.
