### ISSUE TITLE
Chain of trust shoud extract the tasks from `.taskcluster.yml` after rendering, rather than before.

### ISSUE THREAD

**Issue by tomprince** [mozilla-releng/scriptworker#239]
That would avoid issues like https://bugzilla.mozilla.org/show_bug.cgi?id=1470886#c9 where changing the template in a way that doesn't affect the rendered definition caused scriptworker verification to fail.

**Comment by escapewindow** [comment]
This might also help us remove the hardcoded assumption that the decision task should be `tasks[0]`; perhaps the decision task only needs to be one of the tasks in `tasks`?
