### ISSUE TITLE
If child script dies, scriptworker reports the task as "completed"

### ISSUE THREAD

**Issue by mitchhentges** [mozilla-releng/scriptworker#274]
While attempting to reproduce #260, I've found that killing the child (e.g.: `SIGSEGV`, `SIGPWR` or just boring `SIGKILL`) doesn't cause `scriptworker` to report the failure - instead the task is marked as "completed".
[example build that died due to `SIGSEGV`](https://tools.taskcluster.net/groups/Qn_DXY0qSE6NEylj6OYFpw/tasks/YaA2dyHzS76lgY5ovIOvTg/details).

This could cause follow-up builds to fail since builds they depend on are marked as successful, even though required artifacts may not have been produced

**To reproduce:**
1. Set up `scriptworker` locally
2. Set the `task_script` of `scriptworker` to a real script, like `signingscript`
3. Edit the "real script" to ensure that it doesn't fail, but also takes a while to complete (e.g. add a `time.sleep(...)`)
4. Trigger a task on your `scriptworker`
5. `kill -SEGV $PID`, where `$PID` is the process ID of the `signingscript` process

**Comment by escapewindow** [comment]
Hm. I think we check the exit code of the script. This is 0?

We could make *scripts do something standard, like touch a tmpfile at the beginning and remove the tmpfile if we completed successfully, that scriptworker can use to check status. Doing so uniformly would be easier if we had a monorepo ;-)

**Comment by mitchhentges** [comment]
I think we can lean on the process's exit code here for sure :)

**Comment by escapewindow** [comment]
I think we fixed this in #387.
