### ISSUE TITLE
schema_file should not be a recommended part of config

### ISSUE THREAD

**Issue by mitchhentges** [mozilla-releng/scriptworker#287]
See the [original pushapkscript ticket](https://github.com/mozilla-releng/pushapkscript/issues/59)

The `schema_file` defines what is a valid task structure for the _current_ version of each `$script`. Being able to configure this schema file means that our code can't trust that validation is ensuring incoming data is in the right format. As source code changes to expect a different schema, the `schema_file` should be updated in tandem, and should be expected to be applied in tandem, too.

So, we should statically refer to the version of `schema_file` that ships with each `$script`. This has two benefits:
* Less variability at runtime
* Less configuration for end-users

-----

This ticket requires the following:
1. ~~`scriptworker` should be able to have the schema handed directly from the dependent scripts via arguments~~
2. ~~Each `$script` should be updated to provide `schema_file` directly, and should remove `schema_file` from the configuration/context~~
3. ~~`scriptworker` should no longer be able to pull `schema_file` from configuration~~

[EDIT](https://github.com/mozilla-releng/scriptworker/issues/287#issuecomment-449768770):
* All scripts will provide `schema_file` as part of the "default config" passed to `scriptworker`.
* All scripts will no longer advertise `schema_file` as an editable property in the config file (though, at a technical level, it still will be)
* Puppet configuration will be updated to no-longer provide `schema_file`
* No changes to the `scriptworker` API

**Comment by escapewindow** [comment]
@mitchhentges , I see a lot of work around changing script configs here and elsewhere. You're aware that releng controls puppet which controls script_config.json, correct?

**Comment by mitchhentges** [comment]
Affirmative - once all the scripts have been updated to no longer require having the schema provided in the config, I'll update the `script_config.json` for each script in puppet :+1:

**Comment by escapewindow** [comment]
I mean removing the ability to specify things in script_config.json and scriptworker.yaml does very little to improve security, since we control all the pieces. Let's make sure the other rationales are strong enough for these changes to be worth it.

**Comment by mitchhentges** [comment]
The goal of this change is not to enhance security, it's to improve confidence that our tasks are properly validated against the running version of `$script`

**Comment by JohanLorenzo** [comment]
Looks like the agreement happened in https://github.com/mozilla-releng/signingscript/pull/99#issuecomment-450679904. I'll good with the plan too! :slightly_smiling_face:

**Comment by escapewindow** [comment]
We bake in the entire script, including schema file, in docker images. We no longer use puppetagain for scriptworkers. I think we're done here?

Related: https://github.com/mozilla-releng/scriptworker-scripts/issues/171
