### ISSUE TITLE
[client] `schema_file` should not be overrideable

### ISSUE THREAD

**Issue by mitchhentges** [mozilla-releng/scriptworker#289]
Right now, we have a single `default_config` abstraction that is merged with a runtime `config` file.
However, some parts of `default_config` _shouldn't_ be editable at runtime, like [`schema_file`](https://github.com/mozilla-releng/scriptworker/issues/287).

Perhaps instead, we should have three sets of config:
* Runtime config
* Default runtime config
* Hardcoded, per-project config

-----

Edit:
Through the discussion, a couple important points have been encountered:
* There's only been one property discovered so far that shouldn't be overrideable, and that's `schema_file`. We don't need a mechanism to support a full set of "hardcoded" config
* This is specific to the `scriptworker.client` part of scriptworker.

**Comment by escapewindow** [comment]
We control scriptworker.yml and the scriptworker install. It's possibly worth splitting these out, but it will add complexity without necessarily improving security. What are you trying to protect against?

**Comment by mitchhentges** [comment]
The goal for this change isn't specifically to enhance security, but rather to address uncertainty.

Currently, any values we want to pass from `*script => scriptworker` can only be provided through the "config" abstraction:

1. Have a default config
2. Have an external config
3. Merge the configs, overriding defaults with external config

The cost to this abstraction is that there isn't a way to provide a value from `*script => scriptworker` that we _know_ doesn't need to be changed. I would argue that this increases complexity, since we have less guarantees on the runtime state of our scripts.

Arguably, this is in the same vein as immutability in our code itself - though you might control the code base, it increases peace-of-mind if things that don't need to be modifiable _aren't_ modifyable.

**Comment by escapewindow** [comment]
Could we also do that by adding tests in [`check_config`](https://github.com/mozilla-releng/scriptworker/blob/master/scriptworker/config.py#L109-L152) ?

**Comment by mitchhentges** [comment]
I feel like it would be simpler to provide a set of "uneditable" options to `scriptworker`, rather than to give an "overrideable" set, then to assert that the set was not changed for certain keys

**Comment by tomprince** [comment]
> Could we also do that by adding tests in [`check_config`](https://github.com/mozilla-releng/scriptworker/blob/master/scriptworker/config.py#L109-L152) ?

I'm not sure why having a dynamic check is preferable to separating things that have different purpose and lifecycle. I'd rather have the different bits of config statically separated, than have a dynamic check that we don't touch some of the config.

**Comment by escapewindow** [comment]
I still don't see the need. Perhaps if we had more concrete examples + a writeup about the fallout if we don't separate?

**Comment by mitchhentges** [comment]
The only use case I've found so far is for `schema_file`.
For example, imagine if for `pushapkscript`, a worker had defined a custom schema, but then we released a new version with a new property: `google_play_track`. We update the schema we expect so that `google_play_track` is mandatory. When the new release is used on workers, outdated tasks are rejected if they don't match the schema.

However, one worker has defined a custom schema. When the version of `pushapkscript` was updated, the worker's custom schema wasn't updated as well (it wasn't obvious that it had changed). Now, when tasks are arriving that don't have the new `google_play_track` property, they aren't being caught at schema-validation-time. Instead, our script is failing at runtime when we use `payload['google_play_track']!

So, though this will require some work in `scriptworker` to accomplish, it decreases our API surface and increases confidence in releases

**Comment by escapewindow** [comment]
I think a separate config file for a single option seems a bit heavy handed. We may find other use cases in the future.

**Comment by tomprince** [comment]
> I think a separate config file for a single option seems a bit heavy handed. We may find other use cases in the future.

I agree, though I do think we should move that out of the config (which amounts to the same things, in a way).

**Comment by mitchhentges** [comment]
> I think a separate config file for a single option seems a bit heavy handed. We may find other use cases in the future.

Ah, I think that we might be viewing the implementation of this solution a bit differently:
I agree that a new config file is heavy-handed - I don't think that we need a file for this.

I'm considering something more in-code, such as adding `constants` (dictionary) to `sync_main`:
```
# in scriptworker
def sync_main(async_main, config_path, default_config, constants, ...)
```

Or, ideally, just provide the constants one-by-one as needed:
```
# in scriptworker
def sync_main(async_main, config_path, default_config, task_schema, ...)
```

**Comment by escapewindow** [comment]
I still see this as a solution seeking a problem.

**Comment by escapewindow** [comment]
At this point, all of this is controlled in scriptworker-scripts, and is deployed together. I think that means this is no longer an issue, or should be resolved by https://github.com/mozilla-releng/scriptworker-scripts/issues/171 .
