### ISSUE TITLE
Put branch coverage back to 100%

### ISSUE THREAD

**Issue by JohanLorenzo** [mozilla-releng/scriptworker#311]
There are 2 places we miss, currently:
* https://travis-ci.org/mozilla-releng/scriptworker/jobs/493004995#L1226
* https://travis-ci.org/mozilla-releng/scriptworker/jobs/493004995#L124

Spotted in #307 by @escapewindow

**Comment by escapewindow** [comment]
My [remove-gpg branch](https://github.com/escapewindow/scriptworker/commits/remove-gpg) fixes this. Probably [this commit](https://github.com/escapewindow/scriptworker/commit/e8599f842e23812007d4beb56ba34bcb8ab2d7dd).
