### ISSUE TITLE
Committing with the Github's desktop app breaks Chain of Trust

### ISSUE THREAD

**Issue by JohanLorenzo** [mozilla-releng/scriptworker#334]
Error spotted at https://treeherder.mozilla.org/#/jobs?repo=fenix&revision=4cd0d464a7d5e15cc85f29e0dc14fcd127cca4ea&selectedJob=242996267:

```python
2019-04-26T21:26:59 CRITICAL - signing:parent fzYG7Cy0RviQIijkGw8jvg: the runtime task doesn't match any rebuilt definition!
["[('change', 'payload.env.MOBILE_TRIGGERED_BY', ('web-flow', 'sblatz')),\n"
 " ('change',\n"
 "  'metadata.owner',\n"
 "  ('web-flow@users.noreply.github.com', 'sblatz@users.noreply.github.com'))]"]

```

https://api.github.com/repos/mozilla-mobile/fenix/commits/4cd0d464a7d5e15cc85f29e0dc14fcd127cca4ea returns:
```json
 "committer": {
    "login": "web-flow",
  }
```
which points to [this Github user](https://github.com/web-flow):

`git show --format=fuller 4cd0d464a7d5e15cc85f29e0dc14fcd127cca4ea` shows:
```
commit 4cd0d464a7d5e15cc85f29e0dc14fcd127cca4ea
Author:     Sawyer Blatz <sdblatz@gmail.com>
AuthorDate: Fri Apr 26 13:54:38 2019 -0700
Commit:     GitHub <noreply@github.com>
CommitDate: Fri Apr 26 13:54:38 2019 -0700
```

I confirmed with @sblatz that he used Github's desktop app to make this commit. That error happened on other commits of his. 

In https://github.com/mozilla-releng/scriptworker/pull/327, I changed CoT to use the committer data, instead of the author one because of a similar kind of breakage (#326).

We might want to change https://github.com/mozilla-releng/scriptworker/blob/8e97bbd83b9b578565ec57904c966dd6ae4ef0ae/scriptworker/cot/verify.py#L1201 to detect if the committer is `web-flow` and then fall back to the author data instead. We may run into another error if the person who merges the PR is different. Let's check that first.

**Comment by JohanLorenzo** [comment]
@sblatz could you make a commit (on Fenix) with the desktop app and let someone else merge the PR? This data would be useful to assess what's the best fix.

**Comment by sblatz** [comment]
@JohanLorenzo: this is an example of me committing with desktop app and someone else merging: https://github.com/mozilla-mobile/fenix/pull/2121

**Comment by JohanLorenzo** [comment]
Thanks for the link! So, it seems the bug only occurs when someone makes a commit with the desktop app and then merges the PR themselves. 

mozilla-mobile/fenix#2121 shows:
 * A happy chain of Trust: https://tools.taskcluster.net/groups/Qis1NnwdRPWbSNbTTaRgJg/tasks/Os7u1gIBSVm1zR_orfn9dQ/runs/0/logs/public%2Flogs%2Fchain_of_trust.log
 * No `web-flow` in the exposed data https://api.github.com/repos/mozilla-mobile/fenix/commits/d6879e2501948dae6097e25c3b37429351c912da

**Comment by JohanLorenzo** [comment]
https://help.github.com/en/desktop/getting-started-with-github-desktop/authenticating-to-github-using-the-browser might explain why the "Web Flow" user is also used on desktop.

**Comment by MihaiTabara** [comment]
Rolling it out to production workers via https://github.com/mozilla-releng/build-puppet/pull/476

**Comment by JohanLorenzo** [comment]
Hmmm, I don't understand. Even though the change is deployed, the error remains: https://tools.taskcluster.net/groups/UDHP3ZpqSE-PyoDmxl_2sg/tasks/Dr4ies5VSWWpTE96Y2qXdw/runs/1/logs/public%2Flogs%2Fchain_of_trust.log

I'm looking into it

**Comment by JohanLorenzo** [comment]
Actually, the change isn't deployed because the worker is pinned to another environment. Unpinning it.

**Comment by JohanLorenzo** [comment]
I confirm it now works! https://tools.taskcluster.net/groups/UDHP3ZpqSE-PyoDmxl_2sg/tasks/Dr4ies5VSWWpTE96Y2qXdw/runs/2
