### ISSUE TITLE
add user cancel support to scriptworker

### ISSUE THREAD

**Issue by escapewindow** [mozilla-releng/scriptworker#42]
Currently, we poll to reclaimTask every 5 min.
I believe when we do that, we'll be notified if the status of the task changes.
If the status is user-cancel, we should kill the task.
If we also change the polling interval to something smaller (30 seconds or less?) we should cancel the script in a relatively responsive period of time.

**Comment by escapewindow** [comment]
```
14:02 <aki> so for scriptworker, i ignore 409 on reclaimTask because I assume the async reclaimTask request is happening after we finished the task. I should check to see if i'm still running that same task, and then kill it
14:02 <aki> and then reclaimTask more often to catch user-cancel
14:04 <•jonasfj> aki: yeah... also the credentials you use to do the next reclaimTask, reportCompleted/Failed should be the temporary credentials returned from the most recent claimWork/reclaimTask call for the given taskId/runId
```

**Comment by jonasfj** [comment]
Please do some math before you start reclaiming every 30s :)
With a few workers it'll probably be fine... If we did with 3-5k workers sitting in EC2 that would quickly add significant load... hehe

If you have few workers and is interested in being super responsive to cancel task operations you can could also listen for pulse messages including the workers specific `workerId`. But this isn't a scalable solution either as pulse can't handle one connection if you have 3-5k workers.

More workers => more latency.
