### ISSUE TITLE
Phase out longstanding docker-worker CoT key in favor of new keys

### ISSUE THREAD

**Issue by milescrabill** [mozilla-releng/scriptworker#423]
The long-standing worker ed25519 CoT key ([here](https://github.com/mozilla-releng/scriptworker/blob/5aca528/src/scriptworker/constants.py#L82)) has been in use for a long time across taskcluster deployments. It should be phased out in favor of new keys as we produce new images, with the intention of removing it completely.

**Comment by escapewindow** [comment]
Aiui, we'll be able to phase that out once we're fully on GCP docker-worker. Is that accurate?

**Comment by milescrabill** [comment]
Yes, that's my understanding. That might be a long way away, as there are some tasks (valgrind for one) that are currently broken outside of Ubuntu 14.04, which we're only running in AWS right now.

**Comment by escapewindow** [comment]
In theory, we should be on the new key everywhere docker-worker as of today. It's on my list to do a production cot check later this week.
