### ISSUE TITLE
Python 3.6 can't run scriptworker

### ISSUE THREAD

**Issue by JohanLorenzo** [mozilla-releng/scriptworker#47]
Arch Linux published Python 3.6.0, so I got the chance to seem some errors related to this new version. Some dependencies of scriptworker seem broken.

The first error I got should be fixed by tiran/defusedxml#4 . I know there was another error next (if I commented the defusedxml import), but I haven't looked too much into it.

I guess this issue doesn't matter too much for now (I switched back to 3.5). But I'd prefer filing it, in case new contributors come across similar issues.

**Comment by escapewindow** [comment]
https://travis-ci.org/escapewindow/scriptworker/jobs/189611117 has the current test failures on 3.6.

**Comment by escapewindow** [comment]
Mohawk seems to be the first error message I'm hitting locally and in travis.
Once we have a new mohawk release with https://github.com/kumar303/mohawk/pull/33 , we should get past that error.

**Comment by escapewindow** [comment]
After patching those two libraries, I'm now hitting ssl errors connecting to queue.taskcluster.net.  I'm not sure if that's cross platform or osx specific; there's a ton of ssl changes in [the changelog](https://docs.python.org/3.6/whatsnew/changelog.html).

**Comment by escapewindow** [comment]
Running tox in docker (based on the `python:3.6` base image), I was able to get the unit tests green with just the mohawk and defusedxml patches.  That would suggest the ssl errors are OSX specific.  That'll slow my dev work, but won't affect production.

**Comment by escapewindow** [comment]
Resolved by #76 .
