### ISSUE TITLE
Ignore, and then handle, new task properties `projectId` and `taskQueueId`

### ISSUE THREAD

**Issue by djmitche** [mozilla-releng/scriptworker#482]
Per discussion with @escapewindow, we'll handle adding new properties to tasks as follows:
 * scriptworker will have an allowlist of properties that it accepts but does not verify; it will fail on any other unrecognized properties
 * when we add new properties in TC, we'll add them to this allow list, and at the same time file an issue to actually verify them

So in v41, the new fields will be:
* `projectId` - the project for this task, dictating who can manipulate it
* `taskQueueId` - always equal to `{provisionerId}/{workerType}`

**Comment by escapewindow** [comment]
This is done.
