### ISSUE TITLE
bug 1330396 - add a test git repo tarball into scriptworker/test/data

### ISSUE THREAD

**Issue by escapewindow** [mozilla-releng/scriptworker#51]
Currently [two of our tests](https://github.com/mozilla-releng/scriptworker/blob/4d6fb6f67ef8f94676b41755f3c325e30d87cca9/scriptworker/test/test_gpg.py#L593-L605), `test_get_git_revision` and `test_get_latest_tag`, use the current scriptworker git repo for tests.

This is poor for at least two reasons:
1. because we don't know what each person's git repo status will be when they run the tests, we have to run another git command to find the latest revision or the latest tag.  It isn't deterministic.
2. it isn't possible to run the tests without the .git subdir, e.g. from a pip tarball.  The dockerfile currently pushes the .git subdir to the container so we can run unit tests.

Instead, let's

a. create a test git repo, with a few revisions, and a few tags.
b. tar it up and add it to `scriptworker/test/data/`
c. change those two tests to extract that tarball into a tmpdir, and then running the tests against that tmpdir.

we can then have a deterministic latest tag and latest revision.

**Comment by liljaminkev** [comment]
Hi,

So I am creating a test repo on my account with a few revisions of what? The two test mentioned above? old firefox revisions?? 

I'm intrested I just dont know where to begin.

**Comment by escapewindow** [comment]
Hi @liljaminkev !

A test repo would be local, e.g.

```bash
cd tmp
git init test_git_repo
cd test_git_repo
# add a file, create a revision
# add a 2nd file, create a 2nd revision
# tag the first revision
# tag the 2nd revision
# note the tag names and revision sha's for tests
cd ..
tar czvf test_git_repo.tgz test_git_repo
# copy test_git_repo.tgz into scriptworker/test/data and `git add` it
# modify git tests to extract test_git_repo.tgz into a tmpdir and run tests on it
```

**Comment by liljaminkev** [comment]
So I have the folder set up. I essentially did 
$ echo 1234 > file1.c for a file. When making a revision do I just make changes and commit? Should I have made this a .py file? What kinda stuff should be in these files?

**Comment by escapewindow** [comment]
If you look at the tests, we're concerned with the latest revision on 'master' and the latest tag.  We don't actually look at the contents of the files.  When you tag, use `git tag -a` to get an annotated tag.

**Comment by liljaminkev** [comment]
Thanks that helps :)

**Comment by liljaminkev** [comment]
So I think I am doing this right, but I don't know. 
This is what I did. 

... from the file I made before
git add file.c 
git commit -m "my message"
make changes to file 
git commit -m "my message 2"
git tag -a v0.1 -m "ver 0.1"

echo sdfaefadfs > myfile.py
git add myfile.py
git commit -m "mymessage"
make changes to file
git commit -m "changed blah blah blah"
git tag -a v0.12 -m "ver 0.12"

cd .. 

tar czvf test_git_repo.tgz test_git_repo

copy a version of scriptworker in to my macine
cd scriptworker
mkdir ./test/data
cd test/data
copy tar file here
git add test_git_repo.tgz
I'm stuck here because I dont know what to do next or what I did was right. 

Sorry this is my first time doing opensource and working with tags. I usally use git via desktop app.

**Comment by escapewindow** [comment]
First, it's ok to use the desktop app if you want.  You basically want to copy the tarball into [scriptworker/scriptworker/test/data](https://github.com/mozilla-releng/scriptworker/tree/master/scriptworker/test/data) (which should already exist) and add it.  Then you need to modify [the tests](https://github.com/mozilla-releng/scriptworker/blob/master/scriptworker/test/test_gpg.py#L593-L605) to extract it in a tmpdir and run the tests against that directory.  Then run the tests per [the readme](https://github.com/mozilla-releng/scriptworker/blob/master/README.rst) and make sure they ran correctly and you have full test coverage.

If you want to keep using the commandline, search for a good git tutorial like http://stackoverflow.com/questions/315911/git-for-beginners-the-definitive-practical-guide .  You'll probably do a `git status` to see what files you've added, and `git commit` when you want to commit the changes, and a `git push` to push it up to github.  A `--help`, e.g. `git commit --help`, will show you additional commandline options to add and how they change behavior.

**Comment by salman-bhai** [comment]
Hey is this Issue done or still unresolved? I'd like to contribute if it's possible!

**Comment by escapewindow** [comment]
@salman-bhai I haven't seen any work in progress so far, so it's still up for grabs.  Once someone writes a workable patch, we can assign this PR (and/or bugzilla bug) and work towards a landable patch.

**Comment by fuzzmz** [comment]
@salman-bhai, are you still working on this? I can submit a pull request this evening but wouldn't want your work to be for nothing.

**Comment by escapewindow** [comment]
@fuzzmz I haven't seen anyone's work on this yet, so as far as I'm concerned it's still up for grabs.

**Comment by liljaminkev** [comment]
So I modified these lines after copying the tarball in to the folder:

@pytest.mark.asyncio
async def test_get_git_revision():
    parent_dir = os.path.dirname(~Documents/scriptworker/scriptworker/test/data/testfiles.tar.gz)
    expected = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=parent_dir)
    assert await sgpg.get_git_revision(parent_dir) == expected.decode('utf-8').rstrip()


@pytest.mark.asyncio
async def test_get_latest_tag():
    parent_dir = os.path.dirname(~Documents/scriptworker/scriptworker/test/data/testfiles.tar.gz)
    expected = subprocess.check_output(["git", "describe", "--abbrev=0"], cwd=parent_dir)
    assert await sgpg.get_latest_tag(parent_dir) == expected.decode('utf-8').rstrip()


What am I supposed to modify in the scriptworker.yml file?  I tried just doing ./scriptworker.yml inside the scriptworker folder to launch... but it didn't launch. I guess I don't know what you mean by launch scriptworker [config_path]

I also did NO_TESTS_OVER_WIRE=1 python setup.py test but I got a bunch of errors...

**Comment by liljaminkev** [comment]
running test
Searching for virtualenv
Best match: virtualenv 15.1.0
Processing virtualenv-15.1.0-py3.5.egg

Using /Users/Kevin/Documents/scriptworker/.eggs/virtualenv-15.1.0-py3.5.egg
Searching for taskcluster
Best match: taskcluster 1.0.2
Processing taskcluster-1.0.2-py3.5.egg

Using /Users/Kevin/Documents/scriptworker/.eggs/taskcluster-1.0.2-py3.5.egg
Searching for PyYAML
Best match: PyYAML 3.12
Processing PyYAML-3.12-py3.5-macosx-10.12-x86_64.egg

Using /Users/Kevin/Documents/scriptworker/.eggs/PyYAML-3.12-py3.5-macosx-10.12-x86_64.egg
Searching for python-gnupg
Best match: python-gnupg 0.4.0
Processing python_gnupg-0.4.0-py3.5.egg

Using /Users/Kevin/Documents/scriptworker/.eggs/python_gnupg-0.4.0-py3.5.egg
Searching for pexpect
Best match: pexpect 4.2.1
Processing pexpect-4.2.1-py3.5.egg

Using /Users/Kevin/Documents/scriptworker/.eggs/pexpect-4.2.1-py3.5.egg
Searching for jsonschema
Best match: jsonschema 2.6.0
Processing jsonschema-2.6.0-py3.5.egg

Using /Users/Kevin/Documents/scriptworker/.eggs/jsonschema-2.6.0-py3.5.egg
Searching for frozendict
Best match: frozendict 1.2
Processing frozendict-1.2-py3.5.egg

Using /Users/Kevin/Documents/scriptworker/.eggs/frozendict-1.2-py3.5.egg
Searching for defusedxml
Best match: defusedxml 0.5.0rc1
Processing defusedxml-0.5.0rc1-py3.5.egg

Using /Users/Kevin/Documents/scriptworker/.eggs/defusedxml-0.5.0rc1-py3.5.egg
Searching for arrow
Best match: arrow 0.10.0
Processing arrow-0.10.0-py3.5.egg

Using /Users/Kevin/Documents/scriptworker/.eggs/arrow-0.10.0-py3.5.egg
Searching for aiohttp
Best match: aiohttp 1.2.0
Processing aiohttp-1.2.0-py3.5-macosx-10.12-x86_64.egg

Using /Users/Kevin/Documents/scriptworker/.eggs/aiohttp-1.2.0-py3.5-macosx-10.12-x86_64.egg
Searching for async_timeout
Best match: async-timeout 1.1.0
Processing async_timeout-1.1.0-py3.5.egg

Using /Users/Kevin/Documents/scriptworker/.eggs/async_timeout-1.1.0-py3.5.egg
Searching for six<2,>=1.10.0
Best match: six 1.10.0
Processing six-1.10.0-py3.5.egg

Using /Users/Kevin/Documents/scriptworker/.eggs/six-1.10.0-py3.5.egg
Searching for slugid<2,>=1.0.7
Best match: slugid 1.0.7
Processing slugid-1.0.7-py3.5.egg

Using /Users/Kevin/Documents/scriptworker/.eggs/slugid-1.0.7-py3.5.egg
Searching for mohawk<0.4,>=0.3.4
Best match: mohawk 0.3.4
Processing mohawk-0.3.4-py3.5.egg

Using /Users/Kevin/Documents/scriptworker/.eggs/mohawk-0.3.4-py3.5.egg
Searching for requests<3,>=2.4.3
Best match: requests 2.13.0
Processing requests-2.13.0-py3.5.egg

Using /Users/Kevin/Documents/scriptworker/.eggs/requests-2.13.0-py3.5.egg
Searching for ptyprocess>=0.5
Best match: ptyprocess 0.5.1
Processing ptyprocess-0.5.1-py3.5.egg

Using /Users/Kevin/Documents/scriptworker/.eggs/ptyprocess-0.5.1-py3.5.egg
Searching for python-dateutil
Best match: python-dateutil 2.6.0
Processing python_dateutil-2.6.0-py3.5.egg

Using /Users/Kevin/Documents/scriptworker/.eggs/python_dateutil-2.6.0-py3.5.egg
Searching for yarl>=0.8.1
Best match: yarl 0.9.1
Processing yarl-0.9.1-py3.5-macosx-10.12-x86_64.egg

Using /Users/Kevin/Documents/scriptworker/.eggs/yarl-0.9.1-py3.5-macosx-10.12-x86_64.egg
Searching for multidict>=2.1.4
Best match: multidict 2.1.4
Processing multidict-2.1.4-py3.5-macosx-10.12-x86_64.egg

Using /Users/Kevin/Documents/scriptworker/.eggs/multidict-2.1.4-py3.5-macosx-10.12-x86_64.egg
Searching for chardet
Best match: chardet 2.3.0
Processing chardet-2.3.0-py3.5.egg

Using /Users/Kevin/Documents/scriptworker/.eggs/chardet-2.3.0-py3.5.egg
Searching for tox
Best match: tox 2.6.0
Processing tox-2.6.0-py3.5.egg

Using /Users/Kevin/Documents/scriptworker/.eggs/tox-2.6.0-py3.5.egg
Searching for pluggy<1.0,>=0.3.0
Best match: pluggy 0.4.0
Processing pluggy-0.4.0-py3.5.egg

Using /Users/Kevin/Documents/scriptworker/.eggs/pluggy-0.4.0-py3.5.egg
Searching for py>=1.4.17
Best match: py 1.4.32
Processing py-1.4.32-py3.5.egg

Using /Users/Kevin/Documents/scriptworker/.eggs/py-1.4.32-py3.5.egg
running egg_info
writing top-level names to scriptworker.egg-info/top_level.txt
writing entry points to scriptworker.egg-info/entry_points.txt
writing requirements to scriptworker.egg-info/requires.txt
writing dependency_links to scriptworker.egg-info/dependency_links.txt
writing scriptworker.egg-info/PKG-INFO
reading manifest file 'scriptworker.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'config_example.json'
warning: no files found matching 'scriptworker/docs/Makefile'
warning: no files found matching 'scriptworker/docs/conf.py'
warning: no files found matching 'scriptworker/docs/*.rst'
warning: no files found matching 'scriptworker/docs/*.md'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
warning: no previously-included files matching '1000pubkeys' found under directory '*'
writing manifest file 'scriptworker.egg-info/SOURCES.txt'
running build_ext
GLOB sdist-make: /Users/Kevin/Documents/scriptworker/setup.py
py35 create: /Users/Kevin/Documents/scriptworker/.tox/py35
ERROR: invocation failed (exit code 1), logfile: /Users/Kevin/Documents/scriptworker/.tox/py35/log/py35-0.log
ERROR: actionid: py35
msg: getenv
cmdargs: ['/usr/local/opt/python3/bin/python3.5', '-m', 'virtualenv', '--python', '/usr/local/bin/python3.5', 'py35']
env: {'NVM_CD_FLAGS': '', 'USER': 'Kevin', 'CLASSPATH': ':/Users/Kevin/junit/junit-4.12.jar:/Users/Kevin/junit/hamcrest-core-1.3.jar', 'LOGNAME': 'Kevin', 'TERM_SESSION_ID': '48061438-DA59-44F4-A344-0FE306D7C6A1', 'VIRTUAL_ENV': '/Users/Kevin/Documents/scriptworker/.tox/py35', 'LANG': 'en_US.UTF-8', 'Apple_PubSub_Socket_Render': '/private/tmp/com.apple.launchd.BtPB7N4n4J/Render', '__PYVENV_LAUNCHER__': '/usr/local/bin/python3', 'NVM_NODEJS_ORG_MIRROR': 'https://nodejs.org/dist', 'HOME': '/Users/Kevin', 'TERM_PROGRAM_VERSION': '388', 'NVM_IOJS_ORG_MIRROR': 'https://iojs.org/dist', 'PYTHONHASHSEED': '1727361809', 'NVM_DIR': '/Users/Kevin/.nvm', 'JUNIT_HOME': '/Users/Kevin/junit', 'PWD': '/Users/Kevin/Documents/scriptworker', 'PLAT': 'macosx-10.12-x86_64', 'TERM': 'xterm-256color', 'XPC_SERVICE_NAME': '0', 'XPC_FLAGS': '0x0', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.hvHjbNaPJT/Listeners', 'NVM_BIN': '/Users/Kevin/.nvm/versions/node/v5.1.1/bin', 'PATH': '/Users/Kevin/Documents/scriptworker/.tox/py35/bin:/Users/Kevin/.nvm/versions/node/v5.1.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Kevin/bin:/Users/Kevin/junit', 'SHLVL': '1', 'PYTHONDONTWRITEBYTECODE': '1', 'TMPDIR': '/var/folders/86/dnrjz_5j73b2hnx67q_g5xwc0000gn/T/', 'OLDPWD': '/Users/Kevin/Downloads/scriptworker-2.1.1', '_': '/usr/local/bin/python3', '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0', 'TERM_PROGRAM': 'Apple_Terminal', 'NO_TESTS_OVER_WIRE': '1', 'SHELL': '/bin/bash', 'MANPATH': '/Users/Kevin/.nvm/versions/node/v5.1.1/share/man:/usr/local/share/man:/usr/share/man:/Applications/Xcode.app/Contents/Developer/usr/share/man:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man'}

/usr/local/opt/python3/bin/python3.5: No module named virtualenv

ERROR: InvocationError: /usr/local/opt/python3/bin/python3.5 -m virtualenv --python /usr/local/bin/python3.5 py35 (see /Users/Kevin/Documents/scriptworker/.tox/py35/log/py35-0.log)
___________________________________ summary ____________________________________
ERROR:   py35: InvocationError: /usr/local/opt/python3/bin/python3.5 -m virtualenv --python /usr/local/bin/python3.5 py35 (see /Users/Kevin/Documents/scriptworker/.tox/py35/log/py35-0.log)

**Comment by escapewindow** [comment]
@liljaminkev, it looks like someone beat you to the punch with a workable patch.  If you're interested in contributing still, #65 is open.  Sorry about that; it looked like you had lost interest.

One way around the test errors is to use the Dockerfile like in the [readme](https://github.com/mozilla-releng/scriptworker#testing), but you could

```
cp docker/Dockerfile.test Dockerfile
echo {} > secrets.json  # You may not need this, but this may avoid errors
docker build -t scriptworker-test . && docker run -i scriptworker-test bash -il
# in the docker shell, run tox:
NO_TESTS_OVER_WIRE=1 tox
```

However, we're going to go with @fuzzmz's patch in #74 for this issue, once we get the requested followup changes.
