### ISSUE TITLE
Don't run github-push decision tasks on non protected branches

### ISSUE THREAD

**Issue by hneiva** [mozilla-releng/scriptworker#640]
Example: on PRs, it will run 2 decision tasks, one for the push, one for the PR. The push decision will fail (as designed - with scope error).

`.taskcluster.yml` should be changed so decision tasks don't run on `github-push` outside of dev/prod/staging/etc branches.

**Comment by Eijebong** [comment]
This was fixed by https://github.com/mozilla-releng/scriptworker/commit/7c833f6f192bc352b66e7609ea025302df95160e
