### ISSUE TITLE
add helper scripts to the repo

### ISSUE THREAD

**Issue by escapewindow** [mozilla-releng/scriptworker#65]
- we use a lot of gpg homedirs. It would be great to have something like [gpg.sh](https://github.com/escapewindow/docker-signing-server/blob/master/gpg.sh) packaged up in the scriptworker package (in the `data/` subdir?) for debugging purposes.

- we also need to create gpg keypairs on a regular basis.  It would be great to have something like [gpg.py](https://bug1298553.bmoattachments.org/attachment.cgi?id=8792961) packaged up in the scriptworker package.

Both scripts would need to be more generic, but those are good templates to start from.

**Comment by fuzzmz** [comment]
@escapewindow can you give some more info about the helper scripts and what you need them to do? I'd like to work on this issue but before committing to that I'd like to know that I have the time to finish it.

**Comment by escapewindow** [comment]
@fuzzmz,

- [gpg.sh](https://github.com/escapewindow/docker-signing-server/blob/master/gpg.sh) - This is a helper script to run gpg with a given gpg homedir.  The gpg homedir defaults to `~/.gnupg`, but we create a bunch of gpg homedirs in scriptworker.  It's helpful to be able to run things like `--list-keys` in each gpg homedir without having to remember the exact commandline arguments to do so.
    - We need to be able to specify a gpg binary, e.g. `/usr/local/bin/gpg2`. This will be specific to each machine/environment, so this should be in an env var or commandline option.
    - We need to be able to specify a gpg homedir, e.g. `~/.gnupg` or `./tmp-gnupg-home`.  In the [example `gpg.sh`](https://github.com/escapewindow/docker-signing-server/blob/master/gpg.sh), that's hardcoded to `docker/gpg`.  We need to be able to support any gpg homedir, so this should be specifiable by env var or commandline option.

- [gpg.py](https://bug1298553.bmoattachments.org/attachment.cgi?id=8792961) - This is a helper script to create and export gpg keypairs.
    - We probably want commandline options for `GPG_HOME`, `GPG_PATH`, and `HOSTS`.  The script currently hardcodes `cltsign@{host}` as the email address; we should allow for a different username in the commandline options.
    - options on whether to `shutil.rmtree` or not, and to change the default expiration from `2y` would be helpful as well.

The current names aren't very descriptive; we could rename the latter to `create_gpg_keys.py` or something?  I'm also not sure where to put them -- a `contrib/` or `helper_scripts` dir?  We'd want to make sure to package them, which means we'd add them in `MANIFEST.in`.

**Comment by fuzzmz** [comment]
Thanks for the details. I'll start working on this from Monday and should have a PR ready to go in a few days if no-one else beats me to the punch.
