### ISSUE TITLE
Support aiohttp 2.0

### ISSUE THREAD

**Issue by JohanLorenzo** [mozilla-releng/scriptworker#93]
[aiohttp 2.0.0 is out](https://pypi.python.org/pypi/aiohttp/2.0.0). This new version [breaks the tests](https://travis-ci.org/mozilla-releng/scriptworker/jobs/213107382#L335). Time to support this new version!

**Comment by escapewindow** [comment]
11:39 &lt;aki&gt; we probably have to verify http://aiohttp.readthedocs.io/en/stable/migration.html#client-exceptions doesn't break us, as well as the rest, then once we're confident in aiohttp 2.0.0, update scriptworker's deps to aiohttp>=2.0.0

**Comment by escapewindow** [comment]
This was resolved in #94.
